name: c19-data
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1
  - certifi=2020.4.5.1
  - openssl=1.1.1g
  - pip=20.0.2
  - python=3.8.3
  - setuptools=47.1.1
  - sqlite=3.31.1
  - tk=8.6.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - beautifulsoup4
    - numpy==1.18.5
    - pandas==1.0.4
    - python-dateutil
    - pytz
    - pyyaml
    - six
    - soupsieve
    - xlrd
    - hydra-core==1.0.0rc1
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
