name: Scrape AZ

on:
  repository_dispatch:
    types:
      - az
  push:
    paths:
      - 'special/az/**'
  schedule:
    - cron: '0 */8 * * *'

defaults:
  run:
     working-directory: special/az

jobs:
  scrape:
      runs-on: ubuntu-20.04
      strategy:
        fail-fast: false
        matrix:
          command: [diagnostic, serology]
      steps:
        - uses: actions/checkout@v2
        - name: Checkout data repo
          uses: actions/checkout@v2
          with:
            ref: data
            token: ${{ secrets.GITHUB_TOKEN }}
            path: ./_data
        - uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '14.x'
        - name: Install dependencies
          run: npm install
        - name: Run scraper
          run: |
            node az_timeseries.js ${{ matrix.command }} > ../../_data/az_${{ matrix.command }}.csv
        - name: Commit
          if: github.ref == 'refs/heads/master'
          uses: EndBug/add-and-commit@v5
          with:
            branch: data
            cwd: './_data'
            message: Updating AZ data
            add: az_${{ matrix.command }}.csv
            author_name: GitHub Actions
            author_email: actions@github.com
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Archive output artifacts
          uses: actions/upload-artifact@v2
          with:
            name: Data
            path: |
              _data/az_*
