# This workflow will generate the Miniconda environment and run the following, in the c19-data env:

name: Build Links

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages

    - name: Setup Conda env
      run: |
        conda env create -f environment.yml

    - name: Generate links page
      run: |
        eval "$(conda shell.bash hook)"
        conda activate c19-data
        python tools/links.py && mv outputs/index.html docs/links.html

    - name: Compare and commit generated links page
      run: |
          if [ "$(git status --porcelain)" != "" ]; then
            git add -u
            git config user.name github-actions
            git config user.email github-actions@github.com
            git commit -m "Links from $(git rev-parse master)"
            git push
          fi
