# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Conda env
      run: |
        curl -O ~/miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash ~/miniconda.sh -b -p $HOME/miniconda
 
    - name: Install dependencies
      run: |
        $HOME/miniconda/bin/conda env create -f environment.yml
        $HOME/miniconda/bin/conda activate c19-data

    - name: Run Flake8
      run: flake8 
      
