name: Scrape WV

on:
  repository_dispatch:
    types:
      - wv
  push:
    paths:
      - 'special/js_scrapers/**'
  schedule:
    - cron: '0 * * * *'

defaults:
  run:
     working-directory: special/js_scrapers

jobs:
  scrape:
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Checkout data repo
          uses: actions/checkout@v2
          with:
            ref: data
            token: ${{ secrets.GITHUB_TOKEN }}
            path: ./_data
        - uses: actions/cache@v2
          with:
            path: ~/.npm
            key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              ${{ runner.os }}-node-
        # there's an extremely irritating DNS bug somewhere (https://github.com/actions/virtual-environments/issues/798)
        # and swapping out the resolver is a weird workaround. Otherwise, app.powerbigov.us won't resolve
        - name: DNS nonsense
          run: sudo ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf
        - name: Use Node.js
          uses: actions/setup-node@v1
          with:
            node-version: '14.x'
        - name: Install dependencies
          run: npm install
        - name: Run scraper
          run: |
            node wv_timeseries.js > ../../_data/wv_lab_tests.csv
        - name: Commit
          if: github.ref == 'refs/heads/master'
          uses: EndBug/add-and-commit@v5
          with:
            branch: data
            cwd: './_data'
            message: Updating WV data
            add: wv_lab_tests.csv
            author_name: GitHub Actions
            author_email: actions@github.com
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Archive output artifacts
          uses: actions/upload-artifact@v2
          with:
            name: Data
            path: |
              _data/wv_lab_tests.csv
